Parity
qutip/qutip-tutorials pull request #74
Opened 2023-12-20 07:29 UTC by mcditoos

This adds a notebook tutorial for the parity feature of HEOM

2024-09-09 06:33 UTC, nwlambert requested changes
I left some inline comments.  Would be better to follow the general template in https://github.com/qutip/qutip-tutorials/blob/main/tutorials-v5/template.md  a bit more too, and add some simple tests at the end.  

Main feedback points are the latex at the beginning needs fixing, and the spectral function stuff can be tidied up and explained a bit more.  I can have a go at this if it helps.

2024-09-09 06:33 UTC, nwlambert commented on tutorials-v5/heom/heom-6-parity.md
> +Where $H_{S}$ is the system Hamiltonian, which is divided into three contributions. The electron system hamiltonian ($H_{e}$), the single-mode cavity ($H_{c}$) and the light matter coupling ($H_{ef}$
there is no cavity in this example, better to remove mention of it here and elsewhere.

2024-09-09 06:33 UTC, nwlambert commented on tutorials-v5/heom/heom-6-parity.md
> +$H_{ec} = \sum_{\sigma=\uparrow,\downarrow} g_{ct} (d_{g\sigma}^{\dagger} d_{e\sigma} + d_{e\sigma}^{\dagger} d_{g\sigma} )(a^{\dagger}+a)$
same here, no cavity coupling etc

2024-09-09 06:33 UTC, nwlambert commented on tutorials-v5/heom/heom-6-parity.md
> +$H_{ef}= \sum_{k} \sum_{\alpha=L,R} \sum_{\sigma=\uparrow,\downarrow} g_{\alpha,k} (c_{\alpha,k}^{\dagger} d_{g\sigma}+c_{\alpha,k} d_{g\sigma}^{\dagger})$
To simplify things i would remove the left/right label here. While one can derive this model from a two-lead one, in practise below we only one ''lead'' split up into two spin labelled baths.

2025-04-28 07:03 UTC, nwlambert commented
@gsuarezr maybe you can remove the other changes, and do a quick iteration on this parity notebook so we can get it merged?

2025-04-28 13:50 UTC, gsuarezr commented
I'll close this PR and open a new one! i think It's easier!

2025-04-28 13:50 UTC, closed without merging